import errno

print(errno.E2BIG)
